apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pyspark-flask-app
  labels:
    app: pyspark-flask-app 
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: pyspark-flask-app
  template:
    metadata: 
      labels:
        app: pyspark-flask-app
    spec:
      containers:
      - name: pyspark-container
        image: ranyqb/pyspark-flask-app:0.0.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits: 
            memory: "2Gi"

